/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as DashboardItemsIndexRouteImport } from './routes/dashboard/items/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PostsPostIdEditIndexRouteImport } from './routes/posts/$postId/edit/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardItemsIndexRoute = DashboardItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdEditIndexRoute = PostsPostIdEditIndexRouteImport.update({
  id: '/posts/$postId/edit/',
  path: '/posts/$postId/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/posts/$postId/edit/': typeof PostsPostIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard': typeof DashboardIndexRoute
  '/posts': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/posts/$postId/edit/': typeof PostsPostIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/'
    | '/posts/'
    | '/api/auth/$'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/dashboard/items/'
    | '/posts/$postId/'
    | '/posts/$postId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard'
    | '/posts'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/items'
    | '/posts/$postId'
    | '/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/'
    | '/posts/'
    | '/api/auth/$'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_auth/signup/'
    | '/dashboard/items/'
    | '/posts/$postId/'
    | '/posts/$postId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PostsIndexRoute: typeof PostsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
  PostsPostIdEditIndexRoute: typeof PostsPostIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/items/': {
      id: '/dashboard/items/'
      path: '/items'
      fullPath: '/dashboard/items/'
      preLoaderRoute: typeof DashboardItemsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/edit/': {
      id: '/posts/$postId/edit/'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit/'
      preLoaderRoute: typeof PostsPostIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardItemsIndexRoute: typeof DashboardItemsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardItemsIndexRoute: DashboardItemsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PostsIndexRoute: PostsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
  PostsPostIdEditIndexRoute: PostsPostIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
